const mongoose = require('mongoose');

const subtitleSchema = new mongoose.Schema({
    language: { 
        type: String, 
        required: true,
        enum: ['en', 'vi', 'ko', 'ja', 'zh']
    },
    text: { type: String, required: true },
    style: {
        fontFamily: { type: String, default: 'Arial' },
        fontSize: { type: Number, default: 24 },
        color: { type: String, default: '#FFFFFF' },
        backgroundColor: { type: String, default: '#000000' },
        position: { type: String, enum: ['top', 'center', 'bottom'], default: 'bottom' },
        animation: { type: String, enum: ['none', 'word-by-word', 'fade-in'], default: 'word-by-word' }
    }
}, { _id: false });

const clipSchema = new mongoose.Schema({
    // Reference to original video
    jobId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'Job', 
        required: true,
        index: true
    },
    userId: { 
        type: mongoose.Schema.Types.ObjectId, 
        ref: 'User', 
        required: true,
        index: true
    },

    // Clip metadata
    title: { type: String, required: true },
    description: { type: String },
    
    // Viral scoring
    viralScore: { 
        type: Number, 
        required: true,
        min: 0,
        max: 100,
        index: true
    },
    emotionalPeak: { 
        type: String,
        enum: ['funny', 'inspiring', 'shocking', 'educational', 'dramatic', 'controversial', 'heartwarming', 'motivational', 'informative', 'entertaining', 'emotional', 'other'],
        required: true
    },
    
    // Time boundaries
    startTime: { type: Number, required: true }, // in seconds
    endTime: { type: Number, required: true },   // in seconds
    duration: { type: Number, required: true },  // in seconds

    // Transcript segment for this clip
    transcript: { type: String, required: true },

    // AI Analysis details
    analysis: {
        hookStrength: { type: Number, min: 0, max: 100 }, // First 3 seconds score
        storyArc: { 
            type: String, 
            enum: ['complete', 'cliffhanger', 'teaser', 'insight']
        },
        quotableMoment: { type: String }, // Best quote in clip
        viralElements: [String], // e.g., ['surprise', 'humor', 'controversy']
        aiModel: { type: String, default: 'gemini-2.0-flash-exp' },
        analyzedAt: { type: Date, default: Date.now }
    },

    // Multi-language subtitles
    subtitles: [subtitleSchema],

    // Platform recommendations
    suggestedPlatforms: [{
        type: String,
        enum: ['tiktok', 'youtube-shorts', 'instagram-reels', 'facebook-reels', 'twitter']
    }],
    
    // Hashtags generated by AI
    hashtags: [String],

    // Video processing status
    status: {
        type: String,
        enum: ['pending', 'processing', 'ready', 'failed'],
        default: 'pending',
        index: true
    },
    
    // Output file paths
    videoPath: { type: String }, // Path to generated clip file
    thumbnailPath: { type: String },
    
    // Processing metadata
    processingError: { type: String },
    processedAt: { type: Date },
    
    // User interactions
    views: { type: Number, default: 0 },
    isPublished: { type: Boolean, default: false },
    publishedAt: { type: Date },
    
    // Social media posting
    tiktokPostId: { type: String },
    tiktokPostedAt: { type: Date },
    tiktokUrl: { type: String },
    
    // Soft delete
    isDeleted: { type: Boolean, default: false },
    deletedAt: { type: Date }
}, {
    timestamps: true
});

// Indexes for performance
clipSchema.index({ jobId: 1, viralScore: -1 });
clipSchema.index({ userId: 1, createdAt: -1 });
clipSchema.index({ status: 1, createdAt: -1 });

// Virtual for getting clip URL
clipSchema.virtual('videoUrl').get(function() {
    if (this.videoPath) {
        return `/outputs/clips/${this._id}.mp4`;
    }
    return null;
});

// Ensure virtuals are included in JSON
clipSchema.set('toJSON', { virtuals: true });
clipSchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('Clip', clipSchema);
